import {useEffect, useRef} from "react";
import Head from "next/head";
import {Swiper, SwiperRef, SwiperSlide} from "swiper/react";
import 'swiper/css';
import products from '@/data/products'
import Link from "next/link";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import {useRouter} from "next/router";

export default function ProductPage({ product }: { product: any }) {
    if (!product) return <div>error</div>

    const router = useRouter();
    const swiperRef = useRef<SwiperRef>(null);

    useEffect(() => {
        swiperRef.current?.swiper?.slideTo(product.index)
    });

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="full-page" style={{background: '#FCFAF2'}}>
                <LanguageSwitcher/>
                <header className="header-box">
                    <img src="/assets/images/logo/logo.svg" alt="logo"/>
                </header>
                <main className="main-box">
                    <section className="home-sweet-biggest-banner">
                        <Swiper
                            ref={swiperRef}
                            slidesPerView={1}
                            freeMode
                            watchSlidesProgress
                        >
                            <div className="swiper-wrapper">
                                <SwiperSlide>
                                    <div>
                                        <picture>
                                            <source srcSet="/assets/images/products/REVITALIZING-OIL.webp"
                                                    type="image/webp"/>
                                            <source srcSet="/assets/images/products/REVITALIZING-OIL.png"
                                                    type="image/png"/>
                                            <img className="matrix-image"
                                                 src="/assets/images/products/REVITALIZING-OIL.png" alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                    <div>
                                        <picture>
                                            <source srcSet="/assets/images/products/REVITALIZING-OIL-BOX.webp"
                                                    type="image/webp"/>
                                            <source srcSet="/assets/images/products/REVITALIZING-OIL-BOX.png"
                                                    type="image/png"/>
                                            <img src="/assets/images/products/REVITALIZING-OIL-BOX.png" alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide>
                                    <div>
                                        <picture>
                                            <source
                                                srcSet="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM.webp"
                                                type="image/webp"/>
                                            <source
                                                srcSet="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM.png"
                                                type="image/png"/>
                                            <img className="matrix-image"
                                                 src="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM.png"
                                                 alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                    <div>
                                        <picture>
                                            <source
                                                srcSet="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM-BOX.webp"
                                                type="image/webp"/>
                                            <source
                                                srcSet="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM-BOX.png"
                                                type="image/png"/>
                                            <img src="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM-BOX.png"
                                                 alt="" loading="lazy"/>
                                        </picture>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide>
                                    <div>
                                        <picture>
                                            <source srcSet="/assets/images/products/RETINOL-NIGHT-CREAM.webp"
                                                    type="image/webp"/>
                                            <source srcSet="/assets/images/products/RETINOL-NIGHT-CREAM.png"
                                                    type="image/png"/>
                                            <img className="matrix-image"
                                                 src="/assets/images/products/RETINOL-NIGHT-CREAM.png" alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                    <div>
                                        <picture>
                                            <source srcSet="/assets/images/products/RETINOL-NIGHT-CREAM-BOX.webp"
                                                    type="image/webp"/>
                                            <source srcSet="/assets/images/products/RETINOL-NIGHT-CREAM-BOX.png"
                                                    type="image/png"/>
                                            <img src="/assets/images/products/RETINOL-NIGHT-CREAM-BOX.png" alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide>
                                    <div>
                                        <picture>
                                            <source
                                                srcSet="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM.webp"
                                                type="image/webp"/>
                                            <source
                                                srcSet="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM.png"
                                                type="image/png"/>
                                            <img className="matrix-image"
                                                 src="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM.png"
                                                 alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                    <div>
                                        <picture>
                                            <source
                                                srcSet="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM-BOX.webp"
                                                type="image/webp"/>
                                            <source
                                                srcSet="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM-BOX.png"
                                                type="image/png"/>
                                            <img
                                                src="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM-BOX.png"
                                                alt="" loading="lazy"/>
                                        </picture>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide>
                                    <div>
                                        <picture>
                                            <source srcSet="/assets/images/products/ULTRA-HYDRATING-CREAM.webp"
                                                    type="image/webp"/>
                                            <source srcSet="/assets/images/products/ULTRA-HYDRATING-CREAM.png"
                                                    type="image/png"/>
                                            <img className="matrix-image"
                                                 src="/assets/images/products/ULTRA-HYDRATING-CREAM.png" alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                    <div>
                                        <picture>
                                            <source
                                                srcSet="/assets/images/products/ULTRA-HYDRATING-CREAM-BOX.webp"
                                                type="image/webp"/>
                                            <source
                                                srcSet="/assets/images/products/ULTRA-HYDRATING-CREAM-BOX.png"
                                                type="image/png"/>
                                            <img src="/assets/images/products/ULTRA-HYDRATING-CREAM-BOX.png"
                                                 alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide>
                                    <div>
                                        <picture>
                                            <source
                                                srcSet="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN.webp"
                                                type="image/webp"/>
                                            <source
                                                srcSet="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN.png"
                                                type="image/png"/>
                                            <img className="matrix-image"
                                                 src="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN.png"
                                                 alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                    <div>
                                        <picture>
                                            <source
                                                srcSet="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN-BOX.webp"
                                                type="image/webp"/>
                                            <source
                                                srcSet="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN-BOX.png"
                                                type="image/png"/>
                                            <img src="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN-BOX.png"
                                                 alt="" loading="lazy"/>
                                        </picture>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide>
                                    <div>
                                        <picture>
                                            <source srcSet="/assets/images/products/ANTI-WRINKLE-CREAM.webp"
                                                    type="image/webp"/>
                                            <source srcSet="/assets/images/products/ANTI-WRINKLE-CREAM.png"
                                                    type="image/png"/>
                                            <img className="matrix-image"
                                                 src="/assets/images/products/ANTI-WRINKLE-CREAM.png" alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                    <div>
                                        <picture>
                                            <source srcSet="/assets/images/products/ANTI-WRINKLE-CREAM-BOX.webp"
                                                    type="image/webp"/>
                                            <source srcSet="/assets/images/products/ANTI-WRINKLE-CREAM-BOX.png"
                                                    type="image/png"/>
                                            <img src="/assets/images/products/ANTI-WRINKLE-CREAM-BOX.png" alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide>
                                    <div>
                                        <picture>
                                            <source srcSet="/assets/images/products/EYE-REPAIR-CREAM.webp"
                                                    type="image/webp"/>
                                            <source srcSet="/assets/images/products/EYE-REPAIR-CREAM.png"
                                                    type="image/png"/>
                                            <img className="matrix-image"
                                                 src="/assets/images/products/EYE-REPAIR-CREAM.png" alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                    <div>
                                        <picture>
                                            <source srcSet="/assets/images/products/EYE-REPAIR-CREAM-BOX.webp"
                                                    type="image/webp"/>
                                            <source srcSet="/assets/images/products/EYE-REPAIR-CREAM-BOX.png"
                                                    type="image/png"/>
                                            <img src="/assets/images/products/EYE-REPAIR-CREAM-BOX.png" alt=""
                                                 loading="lazy"/>
                                        </picture>
                                    </div>
                                </SwiperSlide>
                            </div>
                        </Swiper>
                        <nav>
                            <ul>
                                <li>
                                    <Link href="/p/revitalizing-oil">REVITALIZING OIL</Link>
                                </li>
                                <li>
                                    <Link href="/p/spf6uva-brightening-cream">SPF6 UVA/ BRIGHTENING CREAM</Link>
                                </li>
                                <li>
                                    <Link href="/p/retinol-night-cream">RETINOL NIGHT CREAM</Link>
                                </li>
                                <li>
                                    <Link href="/p/antioxidant-vitamin-c-cream">ANTIOXIDANT VITAMIN C CREAM</Link>
                                </li>
                                <li>
                                    <Link href="/p/ultra-hydrating-cream">ULTRA HYDRATING CREAM</Link>
                                </li>
                                <li>
                                    <Link href="/p/cream-for-acne-prone-skin">CREAM FOR ACNE PRONE SKIN</Link>
                                </li>
                                <li>
                                    <Link href="/p/anti-wrinkle-cream">ANTI-WRINKLE CREAM</Link>
                                </li>
                                <li>
                                    <Link href="/p/eye-repair-cream">EYE REPAIR CREAM</Link>
                                </li>
                            </ul>
                        </nav>
                        <div className="product-detail-rg-bar">
                            <article className={product.className}>
                                <h2 style={{ color: '#fff', background: product.backgroundColor }}>{product.translation.title}</h2>
                                <p dangerouslySetInnerHTML={{ __html: product.translation.description }}></p>
                            </article>
                        </div>
                    </section>
                </main>
                <footer className="footer-box">
                    <p>Copyright © 2025 Dermalissa all rights reserved</p>
                </footer>
            </div>
        </>
    );
}

// @ts-ignore
export async function getStaticPaths({ locales }) {
    const paths = []

    for (const locale of locales) {
        for (const product of products) {
            paths.push({
                params: { slug: product.slug },
                locale,
            })
        }
    }

    return {
        paths,
        fallback: false,
    }
}

// @ts-ignore
export async function getStaticProps({ params, locale }) {
    const product = products.find((p) => p.slug === params.slug)

    if (!product) {
        // geçersiz slug varsa redirect yap
        return {
            redirect: {
                destination: `/${locale ? locale + '/' : ''}p/revitalizing-oil`,
                permanent: false, // 307 redirect (geçici)
            },
        }
    }

    return {
        props: {
            product: {
                index: products.indexOf(product),
                className: product.className,
                backgroundColor: product.backgroundColor,
                slug: product.slug,
                translation: product.translations[locale]
            },
        },
    }
}
