import {useEffect, useRef} from "react";
import Head from "next/head";
import {Swiper, SwiperRef, SwiperSlide} from "swiper/react";
import { EffectCreative } from 'swiper/modules';
import 'swiper/css';
import products from '@/data/products'
import Link from "next/link";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import {useRouter} from "next/router";
import {ReactLenis} from 'lenis/react'

export default function ProductPage({ product }: { product: any }) {
    if (!product) return <div>error</div>

    const {locale, locales, defaultLocale, asPath} = useRouter();
    const swiperRef = useRef<SwiperRef>(null);

    useEffect(() => {
        swiperRef.current?.swiper?.slideTo(product.index)
    });

    useEffect(() => {
        const images = document.querySelectorAll('.matrix-image');

        const callback = function () {
            const scrollY = window.scrollY;

            const maxScroll = 600;
            const clampedScroll = Math.min(Math.max(scrollY, 0), maxScroll);

            const rotate = 24 - (clampedScroll / maxScroll) * 24;
            const width = 65 - (clampedScroll / maxScroll) * 10;

            const translateStart = 150;
            const translateMax = 65;

            let translateY = 0;
            if (clampedScroll > translateStart) {
                const translateProgress = (clampedScroll - translateStart) / (maxScroll - translateStart);
                translateY = translateProgress * translateMax;
            }

            images.forEach(image => {
                // @ts-ignore
                image.style.transform = `rotate(${rotate}deg) translateY(${translateY}%)`;
                // @ts-ignore
                image.style.width = `${width}%`;
            });
        };

        window.addEventListener('scroll', callback);

        return () => {
            window.removeEventListener('scroll', callback);
        };
    }, []);

    return (
        <>
            <Head>
                <title>{`Dermalissa - ${product.translation.title}`}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                {locales!.map((lng) => (
                    <link
                        key={lng}
                        rel="alternate"
                        hrefLang={lng}
                        href={`https://www.dermalissa.com/${lng === defaultLocale ? '' : lng + '/'}p/${product.slug}`}
                    />
                ))}

                <link
                    rel="alternate"
                    hrefLang="x-default"
                    href={`https://www.dermalissa.com/p/${product.slug}`}
                />
            </Head>
            <ReactLenis options={{
                duration: 1.2,
                easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
            }} root>
                <div className="full-page" style={{background: '#FCFAF2'}}>
                    <LanguageSwitcher/>
                    <Link href="/">
                        <header className="header-box">
                            <img src="/assets/images/logo/logo.svg" alt="logo"/>
                        </header>
                    </Link>
                    <main className="main-box">
                        <section className="home-sweet-biggest-banner">
                        <Swiper
                                ref={swiperRef}
                                slidesPerView={1}
                                freeMode
                                watchSlidesProgress
                                grabCursor
                                effect="creative"
                                creativeEffect={{
                                    prev: {
                                        shadow: true,
                                        translate: [0, 0, -400],
                                    },
                                    next: {
                                        translate: ['100%', 0, 0],
                                    },
                                }}
                                modules={[EffectCreative]}
                            >
                                <div className="swiper-wrapper">
                                    <SwiperSlide>
                                        <div>
                                            <div>
                                                <picture>
                                                    <source srcSet="/assets/images/products/REVITALIZING-OIL.webp"
                                                            type="image/webp"/>
                                                    <source srcSet="/assets/images/products/REVITALIZING-OIL.png"
                                                            type="image/png"/>
                                                    <img className="matrix-image"
                                                         src="/assets/images/products/REVITALIZING-OIL.png" alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                            <div>
                                                <picture>
                                                    <source srcSet="/assets/images/products/REVITALIZING-OIL-BOX.webp"
                                                            type="image/webp"/>
                                                    <source srcSet="/assets/images/products/REVITALIZING-OIL-BOX.png"
                                                            type="image/png"/>
                                                    <img src="/assets/images/products/REVITALIZING-OIL-BOX.png" alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                        </div>
                                    </SwiperSlide>
                                    <SwiperSlide>
                                        <div>
                                            <div>
                                                <picture>
                                                    <source
                                                        srcSet="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM.webp"
                                                        type="image/webp"/>
                                                    <source
                                                        srcSet="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM.png"
                                                        type="image/png"/>
                                                    <img className="matrix-image"
                                                         src="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM.png"
                                                         alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                            <div>
                                                <picture>
                                                    <source
                                                        srcSet="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM-BOX.webp"
                                                        type="image/webp"/>
                                                    <source
                                                        srcSet="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM-BOX.png"
                                                        type="image/png"/>
                                                    <img src="/assets/images/products/SPF6-UVA-BRIGHTENING-CREAM-BOX.png"
                                                         alt="" loading="lazy"/>
                                                </picture>
                                            </div>
                                        </div>
                                    </SwiperSlide>
                                    <SwiperSlide>
                                        <div>
                                            <div>
                                                <picture>
                                                    <source srcSet="/assets/images/products/RETINOL-NIGHT-CREAM.webp"
                                                            type="image/webp"/>
                                                    <source srcSet="/assets/images/products/RETINOL-NIGHT-CREAM.png"
                                                            type="image/png"/>
                                                    <img className="matrix-image"
                                                         src="/assets/images/products/RETINOL-NIGHT-CREAM.png" alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                            <div>
                                                <picture>
                                                    <source srcSet="/assets/images/products/RETINOL-NIGHT-CREAM-BOX.webp"
                                                            type="image/webp"/>
                                                    <source srcSet="/assets/images/products/RETINOL-NIGHT-CREAM-BOX.png"
                                                            type="image/png"/>
                                                    <img src="/assets/images/products/RETINOL-NIGHT-CREAM-BOX.png" alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                        </div>
                                    </SwiperSlide>
                                    <SwiperSlide>
                                        <div>
                                            <div>
                                                <picture>
                                                    <source
                                                        srcSet="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM.webp"
                                                        type="image/webp"/>
                                                    <source
                                                        srcSet="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM.png"
                                                        type="image/png"/>
                                                    <img className="matrix-image"
                                                         src="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM.png"
                                                         alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                            <div>
                                                <picture>
                                                    <source
                                                        srcSet="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM-BOX.webp"
                                                        type="image/webp"/>
                                                    <source
                                                        srcSet="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM-BOX.png"
                                                        type="image/png"/>
                                                    <img
                                                        src="/assets/images/products/ANTIOXIDANT-VITAMIN-C-CREAM-BOX.png"
                                                        alt="" loading="lazy"/>
                                                </picture>
                                            </div>
                                        </div>
                                    </SwiperSlide>
                                    <SwiperSlide>
                                        <div>
                                            <div>
                                                <picture>
                                                    <source srcSet="/assets/images/products/ULTRA-HYDRATING-CREAM.webp"
                                                            type="image/webp"/>
                                                    <source srcSet="/assets/images/products/ULTRA-HYDRATING-CREAM.png"
                                                            type="image/png"/>
                                                    <img className="matrix-image"
                                                         src="/assets/images/products/ULTRA-HYDRATING-CREAM.png" alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                            <div>
                                                <picture>
                                                    <source
                                                        srcSet="/assets/images/products/ULTRA-HYDRATING-CREAM-BOX.webp"
                                                        type="image/webp"/>
                                                    <source
                                                        srcSet="/assets/images/products/ULTRA-HYDRATING-CREAM-BOX.png"
                                                        type="image/png"/>
                                                    <img src="/assets/images/products/ULTRA-HYDRATING-CREAM-BOX.png"
                                                         alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                        </div>
                                    </SwiperSlide>
                                    <SwiperSlide>
                                        <div>
                                            <div>
                                                <picture>
                                                    <source
                                                        srcSet="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN.webp"
                                                        type="image/webp"/>
                                                    <source
                                                        srcSet="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN.png"
                                                        type="image/png"/>
                                                    <img className="matrix-image"
                                                         src="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN.png"
                                                         alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                            <div>
                                                <picture>
                                                    <source
                                                        srcSet="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN-BOX.webp"
                                                        type="image/webp"/>
                                                    <source
                                                        srcSet="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN-BOX.png"
                                                        type="image/png"/>
                                                    <img src="/assets/images/products/CREAM-FOR-ACNE-PRONE-SKIN-BOX.png"
                                                         alt="" loading="lazy"/>
                                                </picture>
                                            </div>
                                        </div>
                                    </SwiperSlide>
                                    <SwiperSlide>
                                        <div>
                                            <div>
                                                <picture>
                                                    <source srcSet="/assets/images/products/ANTI-WRINKLE-CREAM.webp"
                                                            type="image/webp"/>
                                                    <source srcSet="/assets/images/products/ANTI-WRINKLE-CREAM.png"
                                                            type="image/png"/>
                                                    <img className="matrix-image"
                                                         src="/assets/images/products/ANTI-WRINKLE-CREAM.png" alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                            <div>
                                                <picture>
                                                    <source srcSet="/assets/images/products/ANTI-WRINKLE-CREAM-BOX.webp"
                                                            type="image/webp"/>
                                                    <source srcSet="/assets/images/products/ANTI-WRINKLE-CREAM-BOX.png"
                                                            type="image/png"/>
                                                    <img src="/assets/images/products/ANTI-WRINKLE-CREAM-BOX.png" alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                        </div>
                                    </SwiperSlide>
                                    <SwiperSlide>
                                        <div>
                                            <div>
                                                <picture>
                                                    <source srcSet="/assets/images/products/EYE-REPAIR-CREAM.webp"
                                                            type="image/webp"/>
                                                    <source srcSet="/assets/images/products/EYE-REPAIR-CREAM.png"
                                                            type="image/png"/>
                                                    <img className="matrix-image"
                                                         src="/assets/images/products/EYE-REPAIR-CREAM.png" alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                            <div>
                                                <picture>
                                                    <source srcSet="/assets/images/products/EYE-REPAIR-CREAM-BOX.webp"
                                                            type="image/webp"/>
                                                    <source srcSet="/assets/images/products/EYE-REPAIR-CREAM-BOX.png"
                                                            type="image/png"/>
                                                    <img src="/assets/images/products/EYE-REPAIR-CREAM-BOX.png" alt=""
                                                         loading="lazy"/>
                                                </picture>
                                            </div>
                                        </div>
                                    </SwiperSlide>
                                </div>
                            </Swiper>
                            <nav>
                                <ul>
                                    {products.map(product => (
                                        <li key={product.slug}>
                                            <Link href={`/p/${product.slug}`} className={asPath === `/p/${product.slug}` ? 'open' : ''}>
                                                {product.translations[locale!].title}
                                            </Link>
                                        </li>
                                    ))}
                                </ul>
                            </nav>
                            <div className="product-detail-rg-bar">
                                <article className={product.className}>
                                    <h2 style={{
                                        color: '#fff',
                                        background: product.backgroundColor
                                    }}>{product.translation.title}</h2>
                                    <p dangerouslySetInnerHTML={{__html: product.translation.description}}></p>
                                </article>
                            </div>
                        </section>
                    </main>
                    <footer className="footer-box">
                        <p>Copyright © 2025 Dermalissa all rights reserved</p>
                    </footer>
                </div>
            </ReactLenis>
        </>
    );
}

// @ts-ignore
export async function getStaticPaths({locales}) {
    const paths = []

    for (const locale of locales) {
        for (const product of products) {
            paths.push({
                params: {slug: product.slug},
                locale,
            })
        }
    }

    return {
        paths,
        fallback: 'blocking',
    }
}

// @ts-ignore
export async function getStaticProps({params, locale, defaultLocale}) {
    const product = products.find((p) => p.slug === params.slug)

    if (!product) {
        // geçersiz slug varsa redirect yap
        return {
            redirect: {
                destination: `/${locale === defaultLocale ? '' :  locale + '/'}p/revitalizing-oil`,
                permanent: false, // 307 redirect (geçici)
            },
        }
    }

    return {
        props: {
            product: {
                index: products.indexOf(product),
                className: product.className,
                backgroundColor: product.backgroundColor,
                slug: product.slug,
                translation: product.translations[locale]
            },
        },
    }
}
